"""
This type stub file was generated by pyright.
"""

from waylay.service import WaylayRESTService
from .import_ import ImportResource

"""REST client for the Waylay ETL Service."""
class ETLService(WaylayRESTService):
    """REST client for the Waylay ETL Service."""
    config_key = ...
    service_key = ...
    gateway_root_path = ...
    resource_definitions = ...
    etl_import: ImportResource


