"""
This type stub file was generated by pyright.
"""

from waylay.service import WaylayResource

"""REST definitions for the import process entity of the etl service."""
DEFAULT_DECORATORS = ...
class ImportResource(WaylayResource):
    """REST Resource for the import process entity of the etl service."""
    link_roots = ...
    actions = ...


