"""
This type stub file was generated by pyright.
"""

from .._base import WaylayRESTService
from .model import ModelResource
from .runtime import RuntimeResource
from .framework import FrameworkResource
from .about import AboutResource

"""REST client for the Waylay Byoml Service."""
class ByomlService(WaylayRESTService):
    """REST client for the Waylay BYOML Service."""
    service_key = ...
    config_key = ...
    gateway_root_path = ...
    resource_definitions = ...
    model: ModelResource
    runtime: RuntimeResource
    framework: FrameworkResource
    about: AboutResource


