"""
This type stub file was generated by pyright.
"""

from .._base import WaylayResource

"""REST definitions for status of Waylay BYOML service."""
DEFAULT_DECORATORS = ...
class AboutResource(WaylayResource):
    """Static status endpoint."""
    actions = ...


