"""
This type stub file was generated by pyright.
"""

import gzip
import csv
import pandas as pd
from typing import Any, Optional
from dataclasses import replace
from tqdm.std import tqdm
from waylay.exceptions import RequestError
from .model import ETLFile, ETL_IMPORT_COLUMN_NAMES, Metric, ParserRequestError, Resource, SeriesInput, SeriesIterator, SeriesSettings, WaylayETLSeriesImport, render_timestamp_zulu
from .import_csv import MeasurementsStoreType, create_import_series_provider, prepare_settings_csv
from .import_dataframe import iter_timeseries_dataframe, prepare_settings_dataframe
from .etlfile import dataframe_from_iterator, list_resources, read_etl_import, read_etl_import_as_stream
from .export_series import create_export_series_provider, export_csv, export_csv_to_dir, export_csv_to_tar_archive, export_csv_to_zip_archive

"""Utilities to parse and render ETL timeseries files."""
def iter_timeseries(*input_data: SeriesInput, settings: SeriesSettings, progress: bool = ..., measurements_store: MeasurementsStoreType = ...) -> SeriesIterator:
    """Create a SeriesIterator for the given input source and settings."""
    ...

def prepare_etl_import(*series_input: SeriesInput, import_file: Optional[ETLFile] = ..., settings: Optional[SeriesSettings] = ..., **settings_args: Any) -> WaylayETLSeriesImport:
    """Update the mapping settings by extracting metadata from an input source."""
    ...

def create_etl_import(etl_import: WaylayETLSeriesImport, progress: bool = ..., measurements_store: MeasurementsStoreType = ...) -> WaylayETLSeriesImport:
    """Create an ETL import file from the given input."""
    ...

