"""
This type stub file was generated by pyright.
"""

from io import TextIOWrapper
from tempfile import SpooledTemporaryFile

"""Utilities."""
class NonClosingTextIOWrapper(TextIOWrapper):
    """TextIOWrapper that doesn't close, but detaches the wrapped buffer when gc-ed."""
    def __del__(self): # -> None:
        """Detach from underlying buffer on deletion."""
        ...
    


class WrappeableSpooledTemporaryFile(SpooledTemporaryFile):
    """Adapted SpooledTemporaryFile so it can be wrapped in a TextIOWrapper."""
    def readable(self) -> bool:
        """Assert readability."""
        ...
    
    def writable(self) -> bool:
        """Assert writability."""
        ...
    
    def seekable(self) -> bool:
        """Assert seekablity."""
        ...
    


