"""
This type stub file was generated by pyright.
"""

"""Legacy placeholder for the Analytics REST service."""
class AnalyticsServiceLegacy:
    """Legacy placeholder."""
    @property
    def query(self):
        """Raise a unsupported issues."""
        ...
    
    @property
    def about(self):
        """Raise a unsupported issues."""
        ...
    


