"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Optional
from .auth import WaylayCredentials

"""Interactive authentication callback for client credentials."""
_http = httpx
log = ...
def tell(message: str): # -> None:
    """Show an interactive authentication message."""
    ...

def ask(prompt: str) -> str:
    """Prompt user for information."""
    ...

def ask_secret(prompt: str) -> str:
    """Prompt user for credential information."""
    ...

def ask_yes_no(prompt: str, default: Optional[bool] = ...) -> bool:
    """Keep prompting the user until response starts with a true or false character."""
    ...

def ask_gateway(default_gateway_url: str): # -> str:
    """Ask for the gateway api in an interactive dialog."""
    ...

def request_migrate_to_gateway_interactive(profile, msg): # -> bool:
    """Asks to migrate to an api-gateway configuration."""
    ...

def request_client_credentials_interactive(default_gateway_url: str = ...) -> WaylayCredentials:
    """Asks interactively for client credentials.

    Default callback provider for an interactive WaylayConfig.
    """
    ...

def request_client_credentials_interactive_legacy(default_accounts_url: str = ...) -> WaylayCredentials:
    """Asks interactively for client credentials.

    Default callback provider for an interactive WaylayConfig.
    """
    ...

def request_store_config_interactive(profile, save_callback): # -> None:
    """Save interactively the storage of credentials as a profile."""
    ...

