"""
This type stub file was generated by pyright.
"""

from waylay.service import WaylayService, WaylayServiceContext
from waylay.config import WaylayConfig
from .tool import TimeSeriesETLTool

"""Internal service with tools for timeseries import and export."""
class TimeSeriesService(WaylayService):
    """Tool service for the timeseries import and export operations."""
    service_key = ...
    etl_tool: TimeSeriesETLTool
    resource_definitions = ...
    def configure(self, config: WaylayConfig, context: WaylayServiceContext) -> TimeSeriesService:
        """Configure endpoints and authentication with given config."""
        ...
    


