"""
This type stub file was generated by pyright.
"""

from waylay.service import WaylayRESTService
from .series import SeriesResource
from .events import EventsResource

"""REST client for the Waylay Data Service (broker)."""
class DataService(WaylayRESTService):
    """REST client for the Waylay Data Service (broker)."""
    config_key = ...
    service_key = ...
    gateway_root_path = ...
    resource_definitions = ...
    series: SeriesResource
    events: EventsResource


