"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Iterator, Optional, Tuple
from waylay.service import WaylayResource

"""REST definitions for the 'series' entity of the 'data' service."""
DEFAULT_DECORATORS = ...
DEFAULT_EXPORT_PAGE_SIZE = ...
RESOURCE_ARG = ...
METRIC_ARG = ...
ADDITIONAL_PARAMS_ARG = ...
class SeriesResource(WaylayResource):
    """REST Resource for the 'series' entity of the 'data' service."""
    link_roots = ...
    actions = ...
    def iter_export(self, resource_id: str, metric: str, page_size: Optional[int] = ..., descending: bool = ..., params: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> Iterator[Tuple[int, Any]]:
        """Fully export a timeseries.

        Uses paging on the '/series/{}/{}/raw' endpoint.

        Parameters
            resource_id: the resource id for the timeseries
            metric: the metric of the timeseries
            page_size: the `limit` size with which data is retrieved using the `export` action
            descending: if true, the series is iterated descending (`order=descending`)
            params: URL params that are passed to the `export` action. These might include:
                params.from: export start timestamp
                params.until: export end timestamp
            kwargs: other params are passed onto the `export` action
        """
        ...
    


