"""
This type stub file was generated by pyright.
"""

from .._base import WaylayRESTService
from .query import QueryResource
from .about import AboutResource

"""REST client for the Waylay Queries Service."""
class QueriesService(WaylayRESTService):
    """REST client for the Waylay Queries Service."""
    service_key = ...
    config_key = ...
    gateway_root_path = ...
    default_root_path = ...
    resource_definitions = ...
    query: QueryResource
    about: AboutResource
    def __init__(self) -> None:
        """Create a QueriesService."""
        ...
    


