"""
This type stub file was generated by pyright.
"""

from .._base import WaylayResource

"""REST definitions for version status of Waylay Queries Service."""
class AboutResource(WaylayResource):
    """Version information."""
    actions = ...


