"""
This type stub file was generated by pyright.
"""

RENDER_OPTIONS = ...
RENDER_MODES = ...
def get_column_names(data, cfg, sep=...): # -> list[Any]:
    """Retrieve columnn names for CSV rendering."""
    ...

def df_to_csv(dataframe, cfg): # -> str:
    """Render a dataframe to a CSV string."""
    ...

def df(pandas_object, render_mode=..., render_options=...): # -> OrderedDict[Any, list[list[Any]] | list[Any] | str]:
    """Render a dataframe to a json-serializable value."""
    ...

def df1(pandas_object, render_mode=..., render_options=...): # -> list[Any] | dict[Any, Any]:
    """Render a dataframe to a json-serializable value."""
    ...

def parse_df(data, render_mode=..., render_options=...): # -> DataFrame:
    """Parse a json-compatible data structure to a Dataframe."""
    ...

def render(value, **render_options): # -> str | int | Any | float | list[Any] | OrderedDict[str, Any] | dict[Any, Any] | None:
    """Convert a value to a json-serializable one."""
    ...

def render_timestamp(value, iso_timestamp=..., **render_options): # -> int:
    """Render a timestamp."""
    ...

