"""
This type stub file was generated by pyright.
"""

from waylay.service import WaylayRESTService
from .bucket import BucketResource
from .object import FolderResource, ObjectResource
from .content import ContentTool
from .about import AboutResource
from .subscription import SubscriptionResource

"""REST client for the Waylay Storage Service."""
class StorageService(WaylayRESTService):
    """REST client for the Waylay Storage Service."""
    config_key = ...
    service_key = ...
    gateway_root_path = ...
    resource_definitions = ...
    bucket: BucketResource
    object: ObjectResource
    folder: FolderResource
    subscription: SubscriptionResource
    about: AboutResource
    content: ContentTool


