"""
This type stub file was generated by pyright.
"""

from waylay.service import WaylayResource

"""REST definitions for version status of Waylay Storage service."""
DEFAULT_DECORATORS = ...
class AboutResource(WaylayResource):
    """Static information about version."""
    link_roots = ...
    actions = ...


