"""
This type stub file was generated by pyright.
"""

from waylay.service import WaylayResource

"""REST definitions for the 'bucket' entity of the 'storage' service."""
BUCKET_NAME_ARG = ...
ADDITIONAL_PARAMS_ARG = ...
class BucketResource(WaylayResource):
    """REST Resource for the 'bucket' entity of the 'storage' service."""
    link_roots = ...
    actions = ...


