"""
This type stub file was generated by pyright.
"""

from datetime import timedelta
from typing import Dict, Iterator, Optional, Union
from waylay.service import WaylayResource

"""REST definitions for the 'object' entity of the 'storage' service."""
BUCKET_NAME_ARG = ...
FOLDER_PATH_ARG = ...
OBJECT_PATH_ARG = ...
PATH_PREFIX_ARG = ...
ADDITIONAL_PARAMS_ARG = ...
def parse_expiry_params(expiry: Union[str, timedelta]) -> Dict[str, int]:
    """Parse sign expiry parameters.

    Input should be either:
    * an ISO period expression
    * a simple string expression `1d` , `6h`, `300s`
    * a `datetime.timedelta` objec
    """
    ...

class FolderResource(WaylayResource):
    """REST Resource for the folder 'object' entity of the 'storage' service."""
    link_roots = ...
    actions = ...


class ObjectResource(WaylayResource):
    """REST Resource for the 'object' entity of the 'storage' service."""
    link_roots = ...
    actions = ...
    def iter_list_all(self, bucket: str, prefix: str, params: Optional[Dict] = ...) -> Iterator[Dict]:
        """Use paging to iterate over all objects."""
        ...
    


