"""
This type stub file was generated by pyright.
"""

from waylay.service import WaylayService, WaylayServiceContext
from waylay.config import WaylayConfig
from .info import InfoTool

"""Utility tools and services for the Python SDK."""
class UtilService(WaylayService):
    """Utility Service for the python SDK."""
    service_key = ...
    info: InfoTool
    resource_definitions = ...
    def configure(self, config: WaylayConfig, context: WaylayServiceContext) -> UtilService:
        """Configure endpoints and authentication with given config."""
        ...
    


