"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import Any, Dict, List, Optional, Union
from waylay.service import WaylayResource, WaylayServiceContext

"""Python SDK Documentation tooling."""
def format_links_html(links: Optional[Dict[str, Dict[str, str]]]) -> str:
    """Format link information to an html string."""
    ...

class InfoTool(WaylayResource):
    """Client tool that exposes information about the provided services, recources and operations."""
    _service_context: WaylayServiceContext
    actions: Dict[str, Any] = ...
    def set_context(self, service_context): # -> None:
        """Configure this tool with a service context."""
        ...
    
    def action_info_df(self, service: Optional[Union[str, List[str]]] = ..., resource: Optional[Union[str, List[str]]] = ..., links: Optional[Union[str, List[str]]] = ..., desc_levels: Optional[Union[str, List[str]]] = ..., include_private: bool = ...) -> pd.DataFrame:
        """Produce a pandas DataFrame with an overview of the provided actions.

Arguments:
    service     filter on the services to be listed
    resource    filter on the resources to be listed
    links       filter on the documentation link names
        """
        ...
    
    def action_info_html(self, service: Optional[Union[str, List[str]]] = ..., resource: Optional[Union[str, List[str]]] = ..., links: Optional[Union[str, List[str]]] = ..., desc_levels: Optional[Union[str, List[str]]] = ...) -> str:
        """Render the service/resource/action listing as an html table.

Arguments:
    service     filter on the services to be listed
    resource    filter on the resources to be listed
    links       filter on the documentation link names
        """
        ...
    


