"""
This type stub file was generated by pyright.
"""

from ._base import WaylayAction, WaylayRESTService, WaylayResource, WaylayService, WaylayServiceContext
from . import _decorators as decorators
from .byoml import ByomlService
from .timeseries import TimeSeriesService
from .resources import ResourcesService
from .storage import StorageService
from .util import UtilService
from .etl import ETLService
from .data import DataService
from .queries import QueriesService

"""Waylay Rest Services."""
SERVICES = ...
