"""
This type stub file was generated by pyright.
"""

from waylay.service import WaylayRESTService
from .resource import ResourceResource
from .resource_type import ResourceTypeResource

"""REST client for the Waylay Resources API Service."""
class ResourcesService(WaylayRESTService):
    """REST client for the main Waylay Resources Service."""
    config_key = ...
    service_key = ...
    gateway_root_path = ...
    resource_definitions = ...
    resource: ResourceResource
    resource_type: ResourceTypeResource


